### ISSUE TITLE
bigger font size

### ISSUE THREAD

**Issue by Li-An** [zonetti/zonote#2]
Hello, quite interesting program. But is there a way to change the font and font size ?

**Comment by zonetti** [comment]
As of right now there is no way to modify any kind of setting, but I agree it could use a bigger font indeed.

For now I just increased the size proportion, I hope it's better for you: https://github.com/zonetti/zonote/releases/tag/v0.4.0

**Comment by Li-An** [comment]
Thanks. It’s better. It’s a little frustrating as when using the program the first thing coming in mind is "Well, how to customize this ?" :-)
