### ISSUE TITLE
Feature Ideas

### ISSUE THREAD

**Issue by jasondavis** [zonetti/zonote#5]
This is really cool and has potential to be a tool that many people would want to use.  It reminds me a little of Freeter Project Dashboards app.

I like that the note file can load tabs of sticky notes.

I like that Markdown is supported along with Image display.

Ideas for content in the note cards:

- [ ] Ability to load iframes
- [ ] Allow drag and drop image file which will then save image to project firectory and link it
- [ ] Add a way to insert buttons into a note that can launch a website, run a command, open a program, etc
- [ ] Currently when I add an image in Markdown,it resizes it to show a tiny version.  Would like it to instead just resize to fit in note.  Also ability to show full image in a popup when clicked on

**Comment by zonetti** [comment]
Hello Jason and thanks for your suggestions. I'll probably rewrite this app with VueJS or something eventually so it's easier to implement new features, I'm just not sure when.
