### ISSUE TITLE
Where is it being saved?

### ISSUE THREAD

**Issue by jojoharry16** [zonetti/zonote#7]
# Preface

God I love this app. It looks expecially amazing on the Macbook screen for some reason, even though it's running Linux, and I can't get enough of it. Apps like this are my favourite part of open source software.

# Actual Problem

The save function... doesn't save. It says that it's saved, and when I close and reopen the app it keeps the changes, but the actual file I opened remains unchanged. Is there a default save location I can access the file from? 

Also, are you still rewriting the app? No pressure, but just wondering if I should look out for updates :)

**Comment by jojoharry16** [comment]
>Correction, it was opening and saving to the wrong file with the same name. Having a `Save as...` feature would be nice, but I'll just be more careful with my naming conventions henceforth

**Comment by zonetti** [comment]
Hello @jojoharry16, I'm really glad you are enjoying the app and I hope it serves you well. Unfortunately at the moment the rewriting is not on my priorities, but I may be able to focus on this project again later this year.

About your issue: I thought about showing the full file path or part of it in the header to avoid these kind of confusion, maybe that should have helped you in this case, but a "save as" function would definitely be useful as well and it's already on the backlog.

Thank you for your feedback :)
